---
title: "Titantic Competiton"
author: "Observer"
date: "October 17, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = setdiff(ls(), lsf.str()))
```
## Included Package
```{r includedPackage, message=F, warning=F}
library(caret)
library(doMC)
library(randomForest)
library(data.table)
library(DMwR)
```
## Set Core
```{r SetCore, message=F, warning=F}
# using multiple processing... comment this if it does not work
registerDoMC(cores = 7)
```
## Load Data
```{r loadData, message=F, warning=F}
dtest<-read.csv("./data/test.csv", header = T)
ds<-read.csv("./data/train.csv", header = T)
dtst = dtest
dtst$Survived=0
dtst$src = 1
ds$src = 0
dall<-rbind(ds,dtst)
dall$Survived = as.factor(dall$Survived)
```

## EDA
```{r EDA, message=F, warning=F}

# Normalized Fare by Pclass
ds$nFare[ds$Pclass==1] = log(ds$Fare[ds$Pclass==1] +0.01) - log(mean(ds$Fare[ds$Pclass==1])+0.01)
ds$nFare[ds$Pclass==2] = log(ds$Fare[ds$Pclass==2] +0.01) - log(mean(ds$Fare[ds$Pclass==2])+0.01)
ds$nFare[ds$Pclass==3] = log(ds$Fare[ds$Pclass==3] +0.01) - log(mean(ds$Fare[ds$Pclass==3])+0.01)
ds$nFare[is.na(ds$nFare)] = 0

ds_m <- ds[!is.na(ds$Age),]
ds_m$Survived <- as.factor(ds_m$Survived)

ggplot(ds_m, aes(SibSp,Age)) + stat_smooth() + geom_point(alpha=0.1)
ggplot(ds_m, aes(factor(Pclass),Age)) + geom_boxplot()
ggplot(ds_m, aes(Parch,Age)) + stat_smooth() + geom_point(alpha=0.1)
ggplot(ds_m[!(ds_m$Embarked==""),], aes(x=Age, fill=Embarked, colour=Embarked)) + geom_density(adjust=1, alpha=0.1)
ggplot(ds_m[ds_m$Pclass==1,], aes(Fare,Age)) + stat_smooth() + geom_point(alpha=0.1)
ggplot(ds_m[ds_m$Pclass==2,], aes(Fare,Age)) + stat_smooth() + geom_point(alpha=0.1)
ggplot(ds_m[ds_m$Pclass==3,], aes(Fare,Age)) + stat_smooth() + geom_point(alpha=0.1)

ggplot(ds_m, aes(Embarked, Survived)) +geom_jitter(alpha=0.1) + geom_point(alpha=0.1)
ggplot(ds_m, aes(SibSp, Survived)) +geom_jitter(alpha=0.1) + geom_point(alpha=0.1)
ggplot(ds_m, aes(Pclass, Survived)) +geom_jitter(alpha=0.1) + geom_point(alpha=0.1)
ggplot(ds_m, aes(Parch, Survived)) +geom_jitter(alpha=0.1) + geom_point(alpha=0.1)
ggplot(ds_m, aes(x=Age, fill=Survived, colour=Survived)) + geom_density(adjust=1, alpha=0.1)
ds_m$AgeDecile = cut(ds_m$Age, c(-2000,7,59,200))

ggplot(ds_m[ds_m$Pclass==1,], aes(x=(nFare), fill=AgeDecile, colour=AgeDecile)) + geom_density(adjust=1, alpha=0.1)
ggplot(ds_m[ds_m$Pclass==2,], aes(x=(nFare), fill=AgeDecile, colour=AgeDecile)) + geom_density(adjust=1, alpha=0.1)
ggplot(ds_m[ds_m$Pclass==3 & as.integer(ds_m$AgeDecile)<3,], aes(x=(nFare), fill=AgeDecile, colour=AgeDecile)) + geom_density(adjust=1, alpha=0.1)

```

## Supporting Functions
```{r Support, message=F, warning=F}
#### function to count number of space in the string
getCountSp <- function(str){
  m<-gregexpr("\\s", str, perl=T)
  return(unlist(length(regmatches(str,m)[[1]])))
}

#### function to generate lookup for cnt per ticket
generate_cnt_by_Ticket<-function(dtf){
  # Create variable for prob to Survive within the same cabin: same cabin usually has same outcome
  dtf<-data.frame(Ticket=dtf$Ticket, Survived=as.integer(dtf$Survived) -1)
  dt<-data.table(dtf)
  lookup<-dt[,list(cnt_ticket = .N), by=Ticket]
  return(lookup)
}

#### function to generate samples from Beta distribution; piror dist. = Beta(1,1) : average = 0.5; posterior = Beta(1+Survived, 1+dead)
generate_BAY_p_ds<-function(i, dtest){
  p <- rbeta(1, dtest$SurvivedTotal[i] + 1, dtest$nsample[i] - dtest$SurvivedTotal[i] + 1 )
  return (p)
}

#### function to generate lookup for cnt per Grpticket and number of survived per GrpTicket
generate_n_Survived_GrpTicket<-function(dtf){
  # Create variable for prob to Survive within the same cabin: same cabin usually has same outcome
  dtf<-data.frame(GrpTicket=dtf$GrpTicket, Survived=as.integer(dtf$Survived) -1)
  dt<-data.table(dtf)
  lookup<-dt[,list(SurvivedTotal = mean(Survived) * .N, nsample = .N), by=GrpTicket]
  return(lookup)
}

#### function to add information in lookup by name into data set
add_info_by_name <- function(dtr, name_, lookup){
  dtr <- merge(x=dtr, y=lookup, by=name_, all.x=T)
  return(dtr)
}

#### function to create variables before the Age prediction
pretreatment <- function(ds){
  ds$Pclass = as.factor(ds$Pclass)
  # Get the title as predictor for Age
  ds$title=""
  ds$title[grepl("Mr\\.", ds$Name)] = "Mr"
  ds$title[grepl("Mrs\\.", ds$Name)] = "Mrs"
  ds$title[grepl("Miss\\.", ds$Name)] = "Miss"
  ds$title[grepl("Master\\.", ds$Name)] = "Master"
  ds$title[grepl("Dr\\.", ds$Name)] = "Dr"
  ds$title[(ds$Sex=="male") & (ds$Age > 12) & (ds$title=="")]="Mr"
  ds$title[(ds$Sex=="male") & (ds$Age <= 11) & (ds$title=="")]="Master"
  ds$title[(ds$Sex=="female") & (ds$Age <= 11) & (ds$title=="")]="Miss"
  ds$title = as.factor(ds$title)
  # Create dummy variable isSingle... 
  ds$noSibSp = as.factor(ds$SibSp == 0)
  ds$isSingle <- as.factor(ds$Parch==0)
  ds$isSinglenoSibSp <- as.factor(ds$SibSp == 0 & ds$Parch==0 )
  ds$hasCabin = as.factor(ds$Cabin=="")
  ds$CabinLet = as.factor(substr(ds$Cabin, 1, 1))
  ds$CabinCnt = as.integer(!ds$Cabin=="") + sapply(ds$Cabin,getCountSp, simplify=T)
  ds$familySz = ds$SibSp + ds$Parch
  
  ds$ln_Fare = log(ds$Fare+0.01)
  ds$nFare[ds$Pclass==1] = log(ds$Fare[ds$Pclass==1] +0.01) - log(mean(ds$Fare[ds$Pclass==1])+0.01)
  ds$nFare[ds$Pclass==2] = log(ds$Fare[ds$Pclass==2] +0.01) - log(mean(ds$Fare[ds$Pclass==2])+0.01)
  ds$nFare[ds$Pclass==3] = log(ds$Fare[ds$Pclass==3] +0.01) - log(mean(ds$Fare[ds$Pclass==3])+0.01)
  ds$nFare[is.na(ds$nFare)] = 0
  
  ds$hasNoChildren = (ds$SibSp==1 & ds$Parch==0)
  ds$r_SibSp_Parch = ((ds$SibSp+0.01)/(ds$SibSp+ds$Parch+0.01))
  
  # Get total number of people per ticket
  lookup<-generate_cnt_by_Ticket(ds)
  ds<-add_info_by_name(ds,"Ticket",lookup)
  # Define the group ticket that has more than 2 people
  ds$GrpTicket = "XXXXXXX"
  ds$GrpTicket[ds$cnt_ticket>1] = as.character(ds$Ticket[ds$cnt_ticket>1])
  
  return(ds)
}

#### function to do Age Prediction
# first stage using linear regression to deal with the interaction
  # Predict Age for missings
  # if isSingle and title is Miss, could be older
  # if isSingle and has a lot of SibSp, could be younger
  # if Pclass is controlled, Fare should reflect the age
  # using log(Age) because Age distribution is right-skewed... except the baby... but mostly right skewed
lm_Age <- function(ds) {
  ds_m <- ds[!is.na(ds$Age),]
  lr_Age<- lm(I(log(Age+0.0001))~title*isSingle + isSingle*SibSp + Parch*I(SibSp>1) + Pclass*nFare + hasCabin*hasNoChildren, data=ds_m)
  print(summary(lr_Age))
  return(lr_Age)
}
# second stage using rf for partition
md_Age <- function(ds) {
  #
  #ds_m <- reSamplebyAge(ds[!is.na(ds$Age),], c(-2000,11,17,30,60,200))
  ds_m <- ds[!is.na(ds$Age),]
  trf_Age<- randomForest(I(log(Age+0.0001))~ title + familySz + pAge_lr + SibSp + Pclass + nFare  + CabinLet + isSinglenoSibSp +  hasNoChildren + r_SibSp_Parch, data=ds_m, importance=TRUE,proximity=TRUE,ntree=500)
  print(varImp(trf_Age))
  return(trf_Age)
}

#### function to create variables after the Age prediction
psttreatment <- function(lm_Ager, trf_Age, ds) {
  ds_m <- ds
  ds_m$pAge_lr = exp(predict(lm_Ager, ds_m))
  ds_m$AgePred <- exp(predict(trf_Age, ds_m))
  ds_m$AgeDecile = cut(ds_m$Age, c(-2000,11,17,30,60,200))
  ds_m$AgePredDecile = cut(ds_m$AgePred, c(-2000,11,17,30,60,200))
  print(table(ds_m$AgeDecile[!is.na(ds_m$Age)],ds_m$AgePredDecile[!is.na(ds_m$Age)]))
  # replace NA
  ds_m$Age[is.na(ds_m$Age)]<-ds_m$AgePred[is.na(ds_m$Age)]
  # cut by decile
  ds_m$AgeDecile = cut(ds_m$Age, c(-2000,11,17,30,60,200))

  return(ds_m)
}


#### function to run the prediction
run_prediction <- function(tgbm2, trf, tsvm, dtest){
  ## Run the data through the model
  dtest$pred.tgbm2 = predict(tgbm2, dtest, "raw")
  dtest$pred.rf = predict(trf, dtest, "raw")
  dtest$pred.svm = predict(tsvm, dtest, "raw")
  dtest$pred.vote = as.factor(
                  as.integer(
                      (as.integer(dtest$pred.rf)-1 + as.integer(dtest$pred.svm)-1 + as.integer(dtest$pred.tgbm2)-1)> 1.5
                    )
                  )
  return(dtest)
}
```

## Data Manipulation
```{r ManupulateData, message=F, warning=F}
dall<-pretreatment(dall)
dall$GrpTicket = as.factor(dall$GrpTicket)
lm_Ager <-  lm_Age(dall)
dall$pAge_lr <- exp(predict(lm_Ager, dall))
trf_Age <- md_Age(dall)
ggplot(dall, aes(factor(title),Age)) + geom_boxplot()
ggplot(dall, aes(factor(title),Survived))  + geom_point(alpha=0.1) +geom_jitter(alpha=0.1)
dall<-psttreatment(lm_Ager, trf_Age,dall)

ds <- dall[dall$src == 0,]
dtest <- dall[dall$src == 1,]

```

## Modeling
```{r Modeling, message=F, warning=F}
ctrl = trainControl(method="repeatedcv", number=20, repeats=10, selectionFunction = "oneSE")
in_train = createDataPartition(ds$Survived, p=.90, list=FALSE)

dtr <- ds[in_train,]
lookup<-generate_n_Survived_GrpTicket(dtr)
dtr<-add_info_by_name(dtr,"GrpTicket", lookup)
dtr$p_Survived<-sapply(1 : length(dtr$nsample), generate_BAY_p_ds, dtest =dtr)

# train model using multiple methods

tune_grid <-  expand.grid(interaction.depth = c(1, 3, 9),
                          n.trees = (1:25)*5,
                          shrinkage = 0.1,
                          n.minobsinnode = 2)
tgbm2 = 
  train(
    Survived ~  Sex + p_Survived + cnt_ticket + title + Pclass + CabinCnt + CabinLet + I(CabinLet=="") + AgeDecile + SibSp + Parch + Embarked + 
              familySz + nFare +isSinglenoSibSp:r_SibSp_Parch, data=dtr, method="gbm", 
    tuneGrid=tune_grid, preProc = c("center", "scale"), metric="Kappa", trControl=ctrl, verbose=FALSE
  )

trf = 
  train(
    Survived ~  Sex + p_Survived + cnt_ticket + title + Pclass + CabinCnt + CabinLet + I(CabinLet=="") + AgeDecile + SibSp + Parch + Embarked + 
              familySz + nFare +isSinglenoSibSp:r_SibSp_Parch, 
    data=dtr, method="rf", metric="Kappa", trControl=ctrl, verbose=FALSE, ntree=350
  )

#method="svmLinear",
tsvm = 
  train(
    Survived ~  Sex + p_Survived + cnt_ticket + title + Pclass + CabinCnt + CabinLet + I(CabinLet=="") + AgeDecile + SibSp + Parch + Embarked + 
              familySz + nFare +isSinglenoSibSp:r_SibSp_Parch, 
    data=dtr, method="svmPoly",tuneLength=4, metric="Kappa", trControl=ctrl, verbose=FALSE, preProc = c("center", "scale")
  )

## Variables importance
varImp(tgbm2)
varImp(trf)
```

## Resampling
```{r Resampling}
resampls = resamples(list(RF = trf,
                          GBM = tgbm2))
difValues = diff(resampls)
summary(difValues)
bwplot(resampls, layout=c(2,1))

resampls = resamples(list(SVM = tsvm,
                          GBM = tgbm2))
difValues = diff(resampls)
summary(difValues)
bwplot(resampls, layout=c(2,1))

resampls = resamples(list(RF = trf,
                          SVM = tsvm))
difValues = diff(resampls)
summary(difValues)
bwplot(resampls, layout=c(2,1))

```

## Verification Using Portion of Training Set
```{r Verify}
test = ds[-in_train,]

test<-add_info_by_name(test,"GrpTicket", lookup)
#backgroud survived rate = Beta(1,1)
test$SurvivedTotal[is.na(test$nsample)]=0
test$nsample[is.na(test$nsample)]=0
test$p_Survived<-sapply(1 : length(test$nsample), generate_BAY_p_ds, dtest =test)

test<-run_prediction(tgbm2, trf, tsvm, test)

confusionMatrix(test$pred.tgbm2, test$Survived)
confusionMatrix(test$pred.rf, test$Survived)
confusionMatrix(test$pred.svm, test$Survived)
confusionMatrix(test$pred.vote, test$Survived)

```

## Generate Summit File for Competition
```{r Generate_Summit}

# Regenerate lookup using all training info
#lookup<-generate_n_Survived_GrpTicket(ds)
# Create variable for prob to Survive within the same cabin
dtest<-add_info_by_name(dtest,"GrpTicket", lookup)

#backgroud survived rate = Beta(1,1)
dtest$SurvivedTotal[is.na(dtest$nsample)]=0
dtest$nsample[is.na(dtest$nsample)]=0
dtest$p_Survived<-sapply(1 : length(dtest$nsample), generate_BAY_p_ds, dtest =dtest)

## Run the data through the model
dtest<-run_prediction(tgbm2, trf, tsvm, dtest)
## Format the summit file and save to ./data/pred.csv
dSummit<-as.data.frame(cbind(dtest$PassengerId,as.integer(dtest$pred.vote)-1))
names(dSummit)=c("PassengerId","Survived")
write.table(dSummit,"./data/pred.csv", row.names=F, col.names = T, sep=",", quote=FALSE)
```